### Curved XShell

#### The input file is a json file containing nurbs curves in the xy plane. 

In [4]:
import sys; sys.path.append('..')
import numpy as np, elastic_rods
from bending_validation import suppress_stdout
from linkage_vis import LinkageViewer
from matplotlib import pyplot as plt
from linkage_utils import order_segments_by_ribbons, get_turning_angle_and_length_from_ordered_rods


curved_file = 'data/test_2/20211014_NURBSmodel.json'



from bending_validation import suppress_stdout as so


from geomdl import exchange
from geomdl import multi
from geomdl.visualization import VisMPL as vis
from geomdl import NURBS
from elasticRodsGH import linkageData

import geomdl

import json
# Import converted data
with open(curved_file) as json_file:
    data = json.load(json_file)

In [6]:
# def clip_alpha(a):
#     if a > 1:
#         return 1
#     if a < 0:
#         return 0
#     return a

# curve_list = []
# curve_function_list = []
# for curve in data['curves']:
#     crv_obj = NURBS.Curve()
#     crv_obj.degree = curve['degree']
#     crv_obj.ctrlpts = curve['cvs']
#     crv_obj.knotvector = [curve['knots'][0]] + curve['knots'] + [curve['knots'][-1]]
#     curve_function_list.append((lambda capture_crv: lambda alpha, correct_orientation: np.array(capture_crv.evaluate_single(clip_alpha(alpha))[:3]) if correct_orientation else np.array(capture_crv.evaluate_single(clip_alpha(1-alpha))[:3]))(crv_obj))
#     curve_list.append(crv_obj)

In [10]:
linkage = linkageData(curved_file)
l = linkage.linkage
print(l)

#l = elastic_rods.RodLinkage(linkage_file, edge_callbacks = curve_function_list, rod_interleaving_type = elastic_rods.InterleavingType.xshell, subdivision = 20)
driver=l.centralJoint()

# l.setMaterial(elastic_rods.RodMaterial('+', 2000, 0.3, [30, 30, 3, 3]))
#l.setMaterial(elastic_rods.RodMaterial('rectangle', 2000, 0.3, [40, 15]))

dpo = elastic_rods.get_designParameter_optimizer(l, 1, 1)
# with so(): cr = dpo.optimize()

jdo = l.dofOffsetForJoint(driver)
fixedVars = list(range(jdo, jdo + 6)) # fix rigid motion for a single joint
# with suppress_stdout(): elastic_rods.compute_equilibrium(l, fixedVars=fixedVars)

view = LinkageViewer(l, width=1024, height=684)
view.show()

Renderer(camera=PerspectiveCamera(aspect=1.4970760233918128, children=(PointLight(color='#999999', position=(0…

In [ ]:
view.update()

In [ ]:
#elastic_rods.compute_equilibrium(l, fixedVars=fixedVars)


RuntimeError: Problem doesn't apply a LEQ constraint.

In [ ]:
l.get_design_parameter_config().restKappa

True

In [8]:
with suppress_stdout(): elastic_rods.compute_equilibrium(l, 0,fixedVars=fixedVars)

In [9]:
l.energy()

362269.17901552573

In [10]:
l.energy(elastic_rods.EnergyType.Bend)

298554.7478936982

In [11]:
l.energy(elastic_rods.EnergyType.Twist)

59293.796440669015

In [12]:
l.energy(elastic_rods.EnergyType.Stretch)

4420.634681158395

In [14]:
rod = l.segment(0).rod


In [15]:
rod.deformedPoints()

[array([-4708.78618295, 11733.93175348,   378.43374282]),
 array([-4695.87168628, 11731.22663273,   374.12407797]),
 array([-4682.97584377, 11728.46463041,   369.79952312]),
 array([-4670.10327325, 11725.63452649,   365.44975979]),
 array([-4657.25458383, 11722.73771075,   361.0733738 ]),
 array([-4644.43038012, 11719.77568637,   356.66889405]),
 array([-4631.63125316, 11716.74993266,   352.23487649]),
 array([-4618.85777684, 11713.6619085 ,   347.76991548]),
 array([-4606.11050848, 11710.51304632,   343.2726492 ]),
 array([-4593.38998874, 11707.30474741,   338.7417657 ]),
 array([-4580.69674001, 11704.03838065,   334.17601081]),
 array([-4568.03126576, 11700.7152789 ,   329.57419437]),
 array([-4555.39404934, 11697.33673664,   324.93519693]),
 array([-4542.78555268, 11693.90400745,   320.25797617]),
 array([-4530.20621488, 11690.41830188,   315.54157314]),
 array([-4517.65645059, 11686.88078527,   310.78511822]),
 array([-4505.13664814, 11683.29257636,   305.98783715]),
 array([-4492.

In [16]:
from open_linkage import open_linkage
def equilibriumSolver(tgtAngle, l, opts, fv):
    return elastic_rods.compute_equilibrium(l, tgtAngle, options=opts, fixedVars=fv)
elastic_rods.benchmark_reset()
with suppress_stdout(): cr = open_linkage(l, driver, 6 * np.pi / 16, 50, view, zPerturbationEpsilon=0, equilibriumSolver=equilibriumSolver, maxNewtonIterationsIntermediate=30, verbose=True, useTargetAngleConstraint=True)
elastic_rods.benchmark_report()

Newton iterations	54.639	51
    Newton iterate	54.5932	1376
        Backtracking	3.9091	1376
            RodLinkage<Real>.setDoFs	3.06976	11510
        Compute descent direction	48.1105	1376
            newton_step	47.8772	1376
                Newton solve	32.8672	1554
                    CHOLMOD Numeric Factorize	27.1702	1553
                    RodLinkage<Real>.massMatrix	0.829043	106
                    Solve	4.05348	1554
                        CHOLMOD Backsub	3.3592	2930
                        CHOLMOD Numeric Factorize	0.0208549	1
                        CHOLMOD Symbolic Factorize	0.060936	1
                RodLinkage<Real>.massMatrix	0.0450511	6
                hessEval	14.5449	1376
                    RodLinkage<Real>.hessian	13.278	1376
                largestMagnitudeEigenvalue	0.283352	12
        Preamble	1.62049	1376
            Callback	0.192884	1376
            RodLinkage<Real>.gradient	0.931759	1376
        RodLinkage<Real>.setDoFs	0.470908	2066
    RodLinkage<Real>.grad

### Read curvature and length from the current structure

In [17]:
def fixed_point_iterate_design_parameters(linkage):
    segment_restlen = []
    for i in range(linkage.numSegments()):
        r = linkage.segment(i).rod
        # compute new kappa
        curr_rest_kappa = r.restKappas()
        deformed_kappa = r.deformedConfiguration().kappa
        new_kappa = []
        for j in range(len(curr_rest_kappa)):
            new_kappa.append(np.array([deformed_kappa[j][0], curr_rest_kappa[j][1]]))

        linkage.segment(i).rod.setRestKappas(new_kappa)
        
        deformed_restlen = r.deformedConfiguration().len
        segment_restlen.append(sum(deformed_restlen) - deformed_restlen[0]/2 - deformed_restlen[-1]/2)
    linkage.setPerSegmentRestLength(segment_restlen)
    elastic_rods.compute_equilibrium(linkage, fixedVars=fixedVars)



In [18]:
for i in range(10):
    fixed_point_iterate_design_parameters(l)

RuntimeError: Problem doesn't apply a LEQ constraint.